### ISSUE TITLE
ignore any "special outfit" with a mask to avoid clipping

### ISSUE THREAD

**Issue by slippycheeze** [Marco4413/CP77-BetterSleeves#1]
I do have "Equipment-EX" installed, which may be involved in this, but regardless, if I use the mod it will cause the mask to visibly clip over the face during movement, certain poses, etc, while in first-person perspective.

The easiest reproduction for me is to put on either the "hazmat suit" or "tactical diving suit" from Phantom Liberty story, but I suspect it applies to anything with a built-in mask like that.

The two item codes from the "debug info" item are:
```
"outfit_01__q305__hazmat_"
"outfit_01__q303__diving_suit_ow_helmet_"
```

I'd suggest you exclude those from rolling of of sleeves as part of the default configuration.

**Comment by Marco4413** [comment]
I'll add those by default asap

**Comment by Marco4413** [comment]
The items will now be blacklisted by default in the next update
